CREATE SCHEMA IF NOT EXISTS school;
SET search_path TO school;

GRANT USAGE ON SCHEMA school TO school_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA school TO school_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA school
    GRANT ALL PRIVILEGES ON TABLES TO school_user;
